CityOfNewYork/NYCOpenRecords

.env.example
public_records_portal/notifications.py
public_records_portal/prr.py
public_records_portal/upload_helpers.py

fixed email attachments for files in public and private upload folders.

feature/OP-460 

---

public_records_portal/models.py
public_records_portal/prr.py
public_records_portal/templates/case.html

Removed the ability for Agency users to change the privacy of the user entered description of the request.

Bugfix/OP-499: Description is never public

---

public_records_portal/db_helpers.py

Updated acknowledgment functionality and extension functionality in v1.0.0.

Hotfix/OP-552: Acknowledgement / Extension Functionality

---

public_records_portal/static/js/case.js

hot fix/OP-556

---

public_records_portal/static/js/newrequestform.js

[OP-601](https://nycrecords.atlassian.net/browse/OP-601)

Bugfix/OP-601: Empty Option before all Agency Dropdowns

---

public_records_portal/static/js/newrequestform.js
public_records_portal/templates/new_request.html

[OP-377](https://nycrecords.atlassian.net/browse/OP-377)

Bugfix/OP-377: Added error for request text and request summary length

---

public_records_portal/prr.py

sanitize update_a_request_acknowledge additional_parameter

bugfix/OP-599 - sanitize update_a_request_acknowledge additional_parameter

---

public_records_portal/prr.py
public_records_portal/views.py

bugfix/OP-596 - sanitize note_text parameter

---

public_records_portal/views.py

sanitize close_reason parameter

bugfix/OP-595 - sanitize close_reason parameter

---

public_records_portal/prflask.py

Also includes the caching fix from OP-592.

Bugfix/OP-594 - Change so that only users logged in as portal administrator can reach admin page.

---

public_records_portal/__init__.py
public_records_portal/templates/manage_request_city_less_js.html
public_records_portal/upload_helpers.py
public_records_portal/views.py

Added message when file is larger than MAX_EMAIL_ATTACHMENT_SIZE but less than MAX_FILE_SIZE

Bugfix/OP-453: Allowing upload of larger files

---

app/templates/main/home.html

Added search button to homepage.

feature/OP-1101: Add options for search and new requests to homepage

---

app/request/forms.py
app/request/views.py
manage.py
tests/forms.py
tests/lib/base.py
tests/request.py

- Set default value for Agency Select field if `current_user` is an agency user.
- Includes unittests for `request.views.view_all` function route and `SearchRequestsForm` class.

Feature/OP-1086: Default Filter for Agency Users - Search Page

---

app/templates/response/add_user_request.html
app/templates/response/add_user_request.js.html
app/templates/response/edit_user_request.html
app/templates/response/edit_user_request.js.html

- Added messaging telling user to hold control to select multiple permissions if user is on Internet Explorer.

Bugfix/OP-1047: IE - Admin must hold CTL button to add permissions

---

app/static/js/request/new-request-agency.js
app/static/js/request/new-request-anon.js

- Contact info error is no longer displayed when name fields are blank. 
- Only error for name fields being blank is shown.

Bugfix/OP-1126: Incorrect contact info error

---

app/static/styles/view_request.css
app/templates/request/view_request.html
app/templates/response/add_note.html

- Hide actions button for public users not logged in.
- Actions section is now below Responses section for logged in public users.

Bugfix/OP-1096: Hide Actions section from public user

---

app/__init__.py
jobs.py

Decrease the size of queries used in the update_request_statuses job to prevent
data from dropping in the network. Update the emails sent out to include tracebacks

BugFix/OP-1153: Decrease Queries for Update Status Job

---

app/request/api/views.py

Updated conditional if statement to prevent public users from seeing private responses.

Bugfix/OP-1155: Public User able to see Private responses when logged in

---

app/lib/file_utils.py
config.py

- Also includes fix to use UPLOAD_SERVING_PATH in config.

Bugfix/OP-1174: File links not opening

---

app/response/utils.py
app/templates/response/add_note.html

- Fix to set public user notes to be release and private

Bugfix/OP-1180: Public User unable to see notes they create

---

app/templates/admin/main.html

Wrap the user GUID on the agency administration page so that the text
does not overlap with the User Name and User Email.

Bugfix/OP-1166: Wrap User GUID on Agency Administration Page.

---

app/__init__.py
app/models.py
app/templates/error/generic.html

- Also includes string representation of class `Anonymous` in `models.py`

Bugfix/OP-1189: Logging via Email

---

app/models.py
app/templates/request/responses/modal_body/notes.html

- Added creator property to class `Responses` to return creator of response and event.

Bugfix/OP-1187: Notes should indicate if they are from Public or Agency users

---

app/auth/utils.py
app/templates/_nyc_gov_footer.html
app/templates/base.js.html
app/templates/request/responses/modal_body/files.html
app/templates/request/responses/modal_body/links.html
config.py

Fixes Include:
- Restrict access to opener in the opened window
- Nginx `upstream prematurely closed connection while reading response header from upstream` error
- redirect and url_for redirects to http not https

Feature/OP-1216: Fixes required to deploy 2.1 to Production

---

app/search/utils.py
app/search/views.py

This PR resolves the following tickets in Jira on the Master Branch:
- [OP-1218](https://nycrecords.atlassian.net/browse/OP-1218): CSV Generation Missing Requests
- [OP-1232](https://nycrecords.atlassian.net/browse/OP-1232): CSV Closed Date Column Has []
- [OS-262](https://nycrecords.atlassian.net/projects/OS/queues/custom/1/OS-262): CSV Generation Missing Requests (Part 2)
Signed-off-by: Joel Castillo <jcastillo@records.nyc.gov>

Hotfix/OP-1218: CSV Generation Missing Requests 

---

app/static/js/plugins/jquery.fileupload.js
app/static/js/plugins/parsley.min.js
app/static/js/request/new-request-agency.js
app/static/js/request/new-request-anon.js
app/templates/base.js.html
app/templates/report/reports.js.html
app/templates/response/add_acknowledgment.js.html
app/templates/response/add_denial.js.html
app/templates/response/add_extension.js.html
app/templates/response/add_file.js.html
app/templates/response/add_note.js.html

Fixes to existing code after we added strict mode to all javascript files.

feature/OP-1224: javascript strict mode fixes

---

app/user/views.py

- Also includes fix to enable/disable super user.

Hotfix/OP-1248: Fix to edit requester information

---

app/response/views.py

Hotfix/OP-1304: Fixed indentation error for send_file_email

---

app/templates/email_templates/email_response_note.html
app/templates/email_templates/response_file_links.html

Fixed errors from QA about extra "/" in note email and extra message for file email.

Feature/OP-1329: bug fixes for note and file email

---

README.md
app/response/utils.py
app/templates/email_templates/_email_response_determinations_list.html
app/templates/email_templates/email_edit_file.html
app/templates/email_templates/email_edit_private_response.html
app/templates/email_templates/email_edit_response.html
app/templates/email_templates/email_private_file_upload.html
app/templates/email_templates/email_response_closing.html
app/templates/email_templates/email_response_denial.html
app/templates/email_templates/email_response_file.html
data/reasons.csv

Adds logic for providing custom reasons within a denial

Hotfix/OP-1343: Denial Reason - Reasons Below

---

app/response/utils.py
app/templates/email_templates/_email_response_determinations_list.html
app/templates/email_templates/email_response_closing.html

Fixes to reasons below for denials and closings.

Hotfix/OP-1343: QA Fixes

---

app/templates/email_templates/email_request_status_changed.html

This PR adds request description and date opened to the nightly request status email.

Feature/OP-1368: FDNY Nightly Report

---

app/templates/email_templates/email_request_status_changed.html

This PR is a hotfix that adds request description and date opened to the nightly request status email.

Hotfix/OP-1368: FDNY Nightly Report

---

app/templates/main/about.html
app/templates/main/faq.html

This PR is a hotfix for the following support tickets:
- https://nycrecords.atlassian.net/browse/OS-413
- https://nycrecords.atlassian.net/browse/OS-414
- https://nycrecords.atlassian.net/browse/OS-417
- https://nycrecords.atlassian.net/browse/OS-418
The changes to the develop branch are made in feature/OP-1241.

Hotfix/OP-1379: Edits to About and FAQ pages

---

app/request/forms.py
app/static/js/request/new-request-agency.js
app/static/js/request/new-request-anon.js
app/static/js/request/new-request-user.js

This PR fixes the bug to prevent multiple requests from being created if the enter button is pressed multiple times on the request page.

Hotfix/OP-1415: Pressing Enter multiple times creates multiple requests

---

app/search/views.py

Add missing positional argument.

Bugfix/OP-1426: Generate CSV Not Working

---

app/templates/response/add_acknowledgment.html

Add the ability to acknowledge with 120 business day time frame.

Feature/OP-1449: Added 120 Business days to Acknowledgment dropdown

---

app/templates/response/add_acknowledgment.html

Add the ability to acknowledge with 120 business day time frame.

Hotfix/OP-1449: Add Additional Acknowledgment Timeframe Option

---

app/request/views.py
app/response/views.py
app/search/views.py

This Pull Request sets a default value for the tz_name value in case the jstz library was unable to get the client timezone (thus returning an empty string).
To test this, change the value of the tz-name input field to empty string before submitting a the 'Create a Request' form.

bugfix/OP-1399: Default value for tz_name is now "America/New_York"

---

app/static/js/request/main.js
app/static/js/request/new-request-agency.js
app/static/js/request/new-request-anon.js
app/static/js/request/new-request-user.js

QA fix for the first merge of OP-1499. Fixed bug where errors were stacking on resubmit.

Feature/OP-1499: Fixed bug where errors were stacking on resubmit

---

app/constants/communication_methods.py
app/response/utils.py
app/response/views.py
app/templates/response/add_reopening.html
app/templates/response/add_reopening.js.html

This PR fixes the functionality of re-opening requests using reasons.
It implements the updated datepicker that disables holidays and weekends, and also fixes some bugs with the retrieval of letter / email templates.
Finally, it makes reason always required so that there is something shown in the response row.

feature/OP-1453: Re-Implementing to fix bugs with original implementation

---

app/static/js/request/main.js
app/static/js/request/new-request-agency.js
app/static/js/request/new-request-anon.js
app/static/js/request/new-request-user.js
app/static/styles/base.css
app/static/styles/home.css
app/static/styles/new_request/new-request.css
app/static/styles/view_all.css
app/static/styles/view_request.css
app/templates/base.html
app/templates/main/home.html
app/templates/navbar.html
app/templates/request/new_request_agency.html
app/templates/request/new_request_anon.html
app/templates/request/new_request_user.html

This PR includes style changes to meet the WCAG Level AA guidelines for color contrast. Color contrast on each page was tested using the tota11y toolkit. I also redesigned the "blue box" instructions to use a collapsible bootstrap panel.

Feature/OP-1179: Global - Color Contrast

---

docs/index.md

Add the documentation for the application.

Initial Docs Directory

---

app/static/js/request/search.js

This PR resolves an issue checking dates when using a datepicker. A custom function was being used to convert dates from MM/DD/YYYY to a JS Date object.

Hotfix/OP-1556: Fix Date Validation 

---

app/static/js/request/search.js

This PR resolves an issue checking dates when using a datepicker. A custom function was being used to convert dates from MM/DD/YYYY to a JS Date object.

Bugfix/OP-1556: Fix Date Validation 

---

app/static/js/request/new-request-agency.js
app/static/js/request/new-request-anon.js
app/static/js/request/new-request-user.js
app/static/styles/new_request/new-request.css
app/templates/request/new_request_agency.html
app/templates/request/new_request_anon.html
app/templates/request/new_request_user.html

Based off this example:
https://accessabilly.com/a-styled-accessible-file-upload/

Feature/OP-1463: Keyboard Accessibility for Choose File Button

---

app/templates/_nyc_gov_footer.html
app/templates/_nyc_gov_header.html
app/templates/base.html
app/templates/main/about.html
app/templates/main/contact.html
app/templates/main/faq.html
app/templates/main/home.html
app/templates/navbar.html
app/templates/report/reports.html
app/templates/request/_view_request_info.html
app/templates/request/new_request_agency.html
app/templates/request/new_request_anon.html
app/templates/request/new_request_user.html
app/templates/request/status.html
app/templates/request/view_request.html

Added aria landmarks for each page in the application except Search since that will be handled by DOITT.

Feature/OP-1175: Global - ARIA Landmark Regions

---

app/templates/main/contact.html
tests/functional/test_main.py

Changed heading structure and added more descriptive aria labels.

Feature/OP-1475: Technical Support Accessibility

---

app/__init__.py
app/celery_config.py
app/jobs.py
requirements/common.txt

In order to run celery beat you need to start the service:
`celery -A celery_worker.celery beat --loglevel=info`

Feature/OP-1484: Automate Update Request Status

---

app/__init__.py
app/celery_config.py
app/jobs.py

In order to start celery beat you need to start the service
celery -A celery_worker.celery beat --loglevel=info

Feature/OP-1573: Auto Update Next Request Number

---

app/templates/report/reports.html
app/templates/report/reports.js.html
tests/functional/test_main.py

Add a submit button to the reports page so that the chart does not refresh until the user clicks submit.

Bugfix/OP-1578: Changed reports chart to only change on submit

---

app/report/views.py
app/templates/report/reports.js.html

Fixed a bug where the user filter on the reports page would only work if you are a super user.

Bugfix/OP-1514: Fixed reports page user filter for agency admins

---

app/templates/request/new_request_agency.html
app/templates/request/status.html

Includes changes for OP-1508 and OP-1238.

Feature/OP-1508: Changed request date to agency received date

---

app/templates/letters/base.html

Added organization into the letter base and only print address line 2 if it exists (currently it prints a blank line)

Feature/OP-1567: Added organization to letter head

---

app/agency/api/views.py
app/request/api/views.py
app/static/js/request/main.js
app/static/js/validation/custom_validators.js
app/templates/custom_request_form_templates/date_template.html
data/custom_request_forms.json
docs/custom_request_forms.md

To test this locally, paste the following JSON into DOT's (0841) agency feature's column:
```
{  
"letters":{  
"generate_letters":false
},
"custom_request_forms":{  
"enabled":true,
"categorized":false,
"expand_by_default":true,
"category_info_text":"",
"category_warning_text":"",
"multiple_request_types":false,
"description_hidden_by_default":false
},
"monitor_agency_requests":[  
],
"specific_request_instructions":{  
"text":"<p>Article 6 of the New York State Public Officers Law (FOIL) allows the public to submit written requests for access to Department of Transportation (DOT) records.</p><p>If you are seeking documents concerning subway or bus service, please see our website at <a rel=\"noopener noreferrer\" target=\"blank\" rel=\"noopener noreferrer\" target=\"blank\" …
```

Bugfix/OP-1594: Custom Forms Need Date Validator

---

app/templates/main/faq.html

Add additional FAQs for date calculations and turned the FAQs into a list for better separation.

Feature/OP-1470: Date Calculation in the FAQ

---

.travis.yml
app/static/js/request/main.js
app/static/js/request/new-request-user.js
app/templates/request/new_request_anon.html
app/templates/request/new_request_anon.js.html
app/templates/request/new_request_user.html

Adds a function in main.js (checkSSN) to look through the provided
string and match the regex for a possible social security number.
The validation on form submission will check the title, description,
and / or custom request forms content for the presence of a matching
string.
If a string match is found, a modal dialog confirmation will appear
giving the user the option to either submit the form or review their
submission to edit any possible PII.

Feature/OP-1620: Check for SSN in Title, Description, and Custom Request Forms

---

app/static/js/request/main.js
app/static/js/request/new-request-agency.js
app/static/js/request/new-request-anon.js
app/static/js/request/new-request-user.js
app/templates/request/_pii_warning_modal.html
app/templates/request/new_request_agency.html
app/templates/request/new_request_anon.html
app/templates/request/new_request_anon.js.html
app/templates/request/new_request_user.html

Prompts anonymous and logged in public users to check for PII before
submitting the FOIL request form. It does not currently affect agency
users when submitting the form.

Feature/OP-1629: PII Prompt for the Requester

---

app/auth/forms.py
app/constants/__init__.py
app/request/forms.py

Adds Puerto Rico to the State list and changes the label on the field to "State / U.S. Territory"

Feature/OP-1636 - Add Puerto Rico to State List

---

docs/saml_nycid_setup.md

Fixing typos in saml_nycid_setup

Update to docs

---

app/templates/report/reports.html

Changes:
- Fixed responses not showing when Notes or Instructions are not editable

OpenRecords v3.4.6

---

app/templates/email_templates/email_confirmation.html
app/templates/email_templates/email_not_onboarded.html

Added request info back into confirmation emails for both on boarded and non on boarded agencies.

Added request info back into confirmation emails

---

app/report/utils.py
openrecords.py

This PR adds cli functionality to run acknowledgment, closing, and monthly metrics reports from the production app server. Reports will be saved to a file directly on the server instead of being emailed.
Example usage:
```
(openrecords)[vagrant@localhost vagrant]$ flask generate-acknowledgement-report
Agency EIN (e.g. 0002): 0836
Date From (e.g. 2000-01-01: 2025-03-13
Date To (e.g. 2000-02-01): 2025-03-20
```
```
(openrecords)[vagrant@localhost vagrant]$ flask generate-closing-report
Agency EIN (e.g. 0002): 0057
Date From (e.g. 2000-01-01: 2025-03-12
Date To (e.g. 2000-02-01): 2025-03-19
```
```
(openrecords)[vagrant@localhost vagrant]$ flask generate-monthly-report
Agency EIN (e.g. 0002): 0810
Date From (e.g. 2000-01-01: 2024-12-01
Date To (e.g. 2000-02-01): 2024-12-31
```

Reports CLI
