CityOfNewYork/NYCOpenRecords

- public_records_portal/models.py
- public_records_portal/prr.py
- public_records_portal/static/js/case.js
- public_records_portal/static/js/manage_request_city.js
- public_records_portal/templates/_response_actions.html
- public_records_portal/templates/case.html
- public_records_portal/views.py
Created an agency description box that opens up a Modal that an agency user can type and modify.
Created conditional to check the following:
- If the Title and Description of Request are set to private the "Agency Description" must be filled out.
- "Agency Description" must be filled out if the request is closed if there is a reference to an offline document in one of its records
- Checks if any of the documents are marked as 'Private' or 'Released and Private"
> Feature/OP-481- Edit Agency Description Box

- public_records_portal/notifications.py
Updated send_emails to pull file from correct folder for email attachments.
[OP-504](https://nycrecords.atlassian.net/browse/OP-504)
> Bugfix/OP-504 

- app/templates/response/add_user_request.js.html
- app/templates/response/edit_user_request.js.html
- Reset presets option in add and edit user form when selecting a user.
- When switching users in the add/edit user option:  
- presets option is reset to `Anonymous User` in the add form
- permissions field is empty in the add form
- presets option is reset to empty in the edit form
- permissions field displays the selected user's permissions
> Bugfix/OP-1041: Reset Presets option when selecting user in Edit User form

- app/static/js/request/new-request-agency.js
Added condition to date picker to prevent keyboard input if key is not tab.
> Disable keyboard input except for tab on create request datepicker

- app/models.py
- app/response/utils.py
- app/templates/request/status.html
- app/templates/request/view_request.html
After the `was_acknowledged` property was fixed, the Reopening of a request shows "Acknowledgement" and "Denial" as the actions. That is not intended and the actions should be as if the Request is "In Progress".
> Bugfix/OP-1173: Actions not showing correct options after Reopen

- app/templates/request/new_request_anon.html
- app/templates/request/new_request_user.html
Use alert-warning to make information about request privacy more visible. Location has been changed to move warning text before field it applies to.
> Bugfix/OP-1159: Make Privacy Text more noticeable

- app/upload/views.py
Due to inconsistencies in the way agencies generate some files,
if an active agency user uploads a file, then the file is automatically,
considered to be valid by the system.
Files will still be scanned by the virus scanner, if enabled, to
prevent viruses from unintentionally being uploaded to the system.
This only ignores the validity of the mime-type generated by the magic
file and the operating system.
> Bugfix/OP-1164: Ignore mime-type if Active Agency User Uploads File

- app/upload/views.py
Due to inconsistencies in the way agencies generate some files,
if an active agency user uploads a file, then the file is automatically,
considered to be valid by the system.
Files will still be scanned by the virus scanner, if enabled, to
prevent viruses from unintentionally being uploaded to the system.
This only ignores the validity of the mime-type generated by the magic
file and the operating system.
> Hotfix/OP-1164: Ignore mime-type if Active Agency User Uploads File

- app/constants/__init__.py
- app/models.py
- app/request/utils.py
- app/search/utils.py
- app/search/views.py
- app/templates/request/_agency_search_form.html
- app/templates/request/_public_search_form.html
- app/templates/request/all.html
- app/templates/request/result_row.html
Change frontend to Display "Date Submitted" rather than "Date Received".
Changed backend to search and sort by "date_created" rather than
"date_submitted".
> bugfix/OP-1168: Use Date Received for Sorting Results.

- app/auth/utils.py
When a public user (anonymous or NYC.ID) logs in with a new account
(defined as a new GUID + Auth Type) a new account will be created,
regardless of the email address on the account.
Agency users will be modified if their user account is using the custom
LDAP user type.
> Bugfix/OP-1156: Only create a new user if not an agency user.

- data/reasons.csv
As per Mayor's Office request, the "Denial - Reasons Attached" reason to the
Denial and Closing options in the OpenRecords portal for Agencies.
> Hotfix/OP-1192: Add "Denial - Reasons Attached" to Closing / Denial Options

- app/response/utils.py
- app/templates/email_templates/email_response_file.html
- app/templates/email_templates/response_file_links.html
Confirmation dialogue for add file workflow was broken per [fb5773ecfbd02959621350d40ff4d9ee723bb133](https://github.com/CityOfNewYork/NYCOpenRecords/commit/fb5773ecfbd02959621350d40ff4d9ee723bb133).
On the rendering of the confirmation template, request is `None` and thus `agency_default_email` is None as well causing the template to not render.
This also includes fixes to file links generating multiple times if there are both release and public and release and private files.
> Bugfix/OP-1197: Adding file email confirmation window

- app/search/utils.py
- app/search/views.py
Add ability to search for FOIL ID without checking filter option.
This commit adds the ability for users to search for a request via FOIL ID from
the basic search box without having to open the advanced search options.
FOIL ID must match the following regular expression:
```
^(FOIL-|foil-|)\d{4}-\d{3}-\d{5}$
```
Valid Matches:
```
FOIL-2017-860-00001
foil-2017-860-00001
2017-860-00001
```
If it matches, then the search will be carried out only on the FOIL ID.
> Feature/OP-1172: Add FOIL ID to Basic Search

- app/auth/utils.py
When querying for a user by their email we now standardize the email to be lowercase to ensure we can find the users record. This is mostly used on the initial login when converting a user from the v2.0 LDAP User AuthType to the SAML User Auth type used in v2.1
> Standardize Email Capitalization for User Queries

- app/request/utils.py
- app/templates/email_templates/email_confirmation.html
- app/templates/email_templates/email_not_onboarded.html
- requirements/requirements.txt
Add a file link to the email confirmation / receipt sent out to the agency and requester when a request is submitted on OpenRecords. This only applies when a file has been added to the request. The link contains a token for the release and private file that the requester has provided as part of their request.
The link is the same for agencies that are live on the portal and agencies that have not begun using the portal to respond to FOIL requests.
Signed-off-by: Joel Castillo <jocastillo@records.nyc.gov>
> bugfix/OP-1303: Add Link to Files Submitted with Request

- app/request/utils.py
- app/request/views.py
- app/templates/email_templates/email_confirmation.html
- app/templates/email_templates/email_not_onboarded.html
Add a file link to the email confirmation / receipt sent out to the agency and requester when a request is submitted on OpenRecords. This only applies when a file has been added to the request. The link contains a token for the release and private file that the requester has provided as part of their request.
The link is the same for agencies that are live on the portal and agencies that have not begun using the portal to respond to FOIL requests.
Signed-off-by: Joel Castillo <jocastillo@records.nyc.gov>
> hotfix/OP-1303: Add Link to Files Submitted with Request

- app/auth/views.py
- app/lib/redis_utils.py
Added a check for a KeyError when trying to delete a session. If the
session does not exist, Redis will raise a KeyError. This means we don't
need to destroy the session and can just move on.
Additionally, if the current_user is anonymous, we don't need to do any
database modifications, because the user does not exist in the Users
table. THerefore we can just redirect to the home page when they click
logout.
Signed-off-by: Joel Castillo <jocastillo@records.nyc.gov>
> Bugfix/OP-1311: Add Error Handling for Anonymous Users and KeyErrors

- app/lib/utils.py
- app/models.py
- app/response/utils.py
- app/response/views.py
Add Duplicate File Check in Files class
Added a new exception `DuplicateFileException` which is raised when a
file is uploaded to a request a second time. This is used in a new check
in the constructor for the Files class in models.py to ensure that a
file is not uploaded twice. This is done to prevent a second email from
being sent out to the requester when a file is uploaded twice due to a
race condition with the Redis keystore.
If a file is uploaded twice, the upload will go through with all valid
files, but any file that was not successfully uploaded will display an
alert at the top of the page after the form has been submitted.
> Bugfix/OP-1304: Duplicate File Uploads Fix

- app/response/utils.py
- app/response/views.py
Due to a misplaced function call inside of a for loop, when a user uploads multiple files, one email per file was being sent out in the format:
Email 1: File A
Email 2: File A, File B
Email 3: File A, File B, File C
etc...
To resolve this issue, the following changes were made to the `send_file_email` function, which generates the emails for the file upload utility.
Email Generation Conditions
- "Release and Public" links provided
- "Release and Private" links provided
- "Private" links provided
- "Release and Public" links and "Release and Private" links provided
- "Release and Public" links and "Private" links provided
- "Release and Private" links and "Private" links provided
- "Release and Public" links and "Release and Private" links and "Private" links provided.
Previously even if …
> Hotfix/OP-1360: Fix Multiple Emails for Multi-File Uploads

- app/response/utils.py
- app/response/views.py
Due to a misplaced function call inside of a for loop, when a user uploads multiple files, one email per file was being sent out in the format:
Email 1: File A
Email 2: File A, File B
Email 3: File A, File B, File C
etc...
To resolve this issue, the following changes were made to the `send_file_email` function, which generates the emails for the file upload utility.
Email Generation Conditions
- "Release and Public" links provided
- "Release and Private" links provided
- "Private" links provided
- "Release and Public" links and "Release and Private" links provided
- "Release and Public" links and "Private" links provided
- "Release and Private" links and "Private" links provided
- "Release and Public" links and "Release and Private" links and "Private" links provided.
Previously even if …
> Fix Multiple Emails for Multi-File Uploads

- build_scripts/db_setup/backup.py
- build_scripts/db_setup/backup.sh
- build_scripts/db_setup/crontab
- build_scripts/db_setup/db_setup.sh
Remember to set environment variables for MAIL_SERVER and MAIL_PORT before running a backup.
You can manually run a backup by doing:
`sudo -u postgres -E /vagrant/build_scripts/db_setup/backup.sh`
You can restore a backup by doing:
`pg_restore -U <DB_USER> -h 127.0.0.1 -C -d <DB_NAME> <NAME_OF_PG_DUMP_FILE>`
> Feature/OP-1334: Add Postgres Backup Script to Build Scripts

- app/request/forms.py
- app/static/js/request/new-request-agency.js
- app/templates/main/about.html
- app/templates/main/faq.html
- app/templates/request/events/row.html
- app/templates/request/responses/modal_body/determinations.html
- app/templates/request/responses/row.html
- app/templates/request/result_row.html
All dates in the portal now use the MM/DD/YYYY format with the exception of dates in determination emails in order to look more formal (Ex. Monday, February 12, 2018) 
This PR also includes text changes for:
- OS-413
- OS-414
- OS-417
- OS-418
> Feature/OP-1241: Use consistent date formatting

- app/templates/email_templates/email_edit_file.html
- app/templates/email_templates/email_edit_private_response.html
- app/templates/email_templates/email_edit_response.html
- app/templates/email_templates/email_footer.html
- app/templates/email_templates/email_private_file_upload.html
- app/templates/email_templates/email_request_status_changed.html
- app/templates/email_templates/email_response.html
- app/templates/email_templates/email_response_acknowledgment.html
- app/templates/email_templates/email_response_extension.html
- app/templates/email_templates/email_response_file.html
- app/templates/email_templates/email_response_instruction.html
- app/templates/email_templates/email_response_link.html
- app/templates/email_templates/email_response_note.html
Reimplementation of the email footer because the previous way resulted in too many inconsistencies especially with emails regarding privacy changes. For most templates, the footer will now be visible at the editing stage instead of the confirmation stage but it will not be editable by the user.
> Feature/OP-1329: Email footer reimplementation

- app/models.py
Fixing a bug found by QA where a user can't upload the same file after deleting it 2 times. This is caused by the original query `file_exists = Files.query.filter_by(request_id=request_id, hash=hash_).one_or_none()` that doesn't produce a list of all the times a file is re uploaded. Modified the query to produce a list and then loop through each file to make sure it has been deleted or else raise a DuplicateFileException.
> Feature/OP-1361: QA fix for multiple re upload attempts

- app/templates/admin/main.html
This PR fixes the bug found during the last 2 maintenances where the add button was not working in the agency administration page. When activating agency users in the agency administration page, if there are currently no active users the add button will not work because it can't find the agency ein of the user.
Fix: Add a hidden field to the user list section that contains the agency ein.
> Bugfix/OP-1389: Add Button Not Working in Agency Administration

- app/templates/admin/main.html
This PR fixes the bug found during the last 2 maintenances where the add button was not working in the agency administration page. When activating agency users in the agency administration page, if there are currently no active users the add button will not work because it can't find the agency ein of the user. 
Fix: Add a hidden field to the user list section that contains the agency ein.
> Hotfix/OP-1389: Add Button Not Working in Agency Administration

- app/static/styles/view_request.css
- app/templates/request/_view_request_info.html
- app/templates/request/view_request.html
This PR adds a section showing what forms of contact the requester provided to the view request page (only viewable by agency users) as well as an alert if no email has been provided.
> Feature/OP-1383: Alert if the requester has no email address

- app/agency/utils.py
- app/models.py
- app/static/js/admin/main.js
- app/templates/admin/main.html
This PR adds a Deactivate button to the Agency Administration page when you are a super user. Deactivating an agency will:
- Remove that agency's requests from the elastic search index
- Toggle that agency's is_active column to False
- Prevent login for users in that agency by toggling their is_agency_active column to False
- Add entries in the Events table for agency_deactivated and agency_user_deactivated
**Note:**
For multi-agency users you have to make sure you switch their primary agency to an active agency before you deactivate an agency they are part of or else you will get an error on the Manage Account page.
> Feature/OP-1388: Deactivate button for Super User

- app/lib/date_utils.py
- app/response/utils.py
- build_scripts/db_setup/backup.py
This PR fixes problems found during MMR metrics. 2 main issues exists:
1) If an anonymous user submits a request the date submitted will be current date + 1 business day. So if an agency user denies/closes on the current date, the time difference between the date submitted and date denied/closed will be -1 which means you denied/closed a request before it was actually submitted
2) If an agency user denies/closes a request on a weekend/holiday those requests will not show up in the final report that is being generated.
Fix: If either of these situations occur, push the denial/closing date to 9:00 AM the following business day.
Concerns:
1) If you push the denial/closing date to the following business day you are effectively working in the future.
2) If you reopen a request that has its …
> Bugfix/OP-1339: Fix denial/closing dates for MMR metrics

- app/models.py
- app/response/utils.py
This PR adds the previous due_date to events for acknowledgments, extensions, and reopening. Also changed 'date' to 'due_date' in val_for_events() for the Determinations class to better reflect what values were changed.
> Bugfix/OP-1396: Previous Due Date is not stored in the Events table

- app/request/forms.py
- app/static/js/request/new-request-agency.js
- app/static/js/request/new-request-anon.js
- app/static/js/request/new-request-user.js
- app/templates/request/new_request_agency.html
- app/templates/request/new_request_anon.html
- app/templates/request/new_request_user.html
This PR fixes the bug to prevent multiple requests from being created if the enter button is pressed multiple times on the request page.
Notes:
- Title field in the request form for anonymous users has been changed from TextAreaField to StringField.
- Updated HTML tags in all request form html files to use double quotes instead of single quotes for consistency.
> Bugfix/OP-1415: Pressing Enter multiple times creates multiple requests

- app/templates/email_templates/email_confirmation.html
Adds the requester title and organization to the confirmation email for a request, if provided. Otherwise shows "Not Provided"
Also updates the name to use the user.name property.
> Bugfix/OP-1420: Add Title and Organization to Confirmation Email

- app/templates/response/add_reopening.html
Agencies with generate letters disabled can't reopen request because the value of the reopening method is missing when the method is email. This is caused by a missing id to the method field in add_reopening.html.
> Hotfix/OP-1445: Reopening Not Working for Agencies with Letters Disabled

- app/templates/response/add_reopening.html
Agencies with generate letters disabled can't reopen request because the value of the reopening method is missing when the method is email. This is caused by a missing id to the method field in add_reopening.html.
> Bugfix/OP-1445: Reopening Not Working for Agencies with Letters Disabled

- app/templates/email_templates/email_response_closing.html
- app/templates/email_templates/email_response_denial.html
- app/templates/response/add_closing.js.html
- app/templates/response/add_denial.js.html
This PR adds an editable line above the appeals paragraph for denial and closing emails. If no text is entered then that line will be hidden on the confirmation step and final email.
> Feature/OP-1447: Move Editable Blank space to before appeals

- app/models.py
- app/request/api/views.py
- app/response/utils.py
- app/templates/request/responses/row.html
This PR adds back in the new pushed closing date calculation that was reverted in commit 5798aeb528b6713f18dc43f1bd5168d40fa0a9bf. Additionally it displays the response rows ordered by their corresponding Event timestamp. This fixes the problem where if the closing date gets pushed and you reopen the request, the the response rows appear out of order.
To test this:
- Force your computer's clock to be Saturday/Sunday
- Create a request as an agency user
- Deny/close that request
- Reopen that request
The response rows should have the reopening as the first row followed by the denial/closing. In the database the date_modified on the denial/closing Response should be the following Monday 9:00 AM (EST).
> Bugfix/OP-1339: Fix Date Closed Calculation

- app/lib/pdf.py
- app/lib/utils.py
- app/response/views.py
This PR resolves an issue when generating envelopes on OpenRecords.
The issue is caused by the `&` character, which is used in LaTeX to represent a tab mark. 
To resolve this, all occurrences of the `&` character are escaped (`\&`).
Difficulties in troubleshooting this error were caused by inadequate information in the `PDFGenerationException` class. Two arguments have been added (`stderr`and `stdout`) to provide additional information for errors caused by os subprocess calls. 
*Original Bug Report*
Error occurs when trying to generate envelopes on some requests.
Error displayed in the following traceback from pdflatex:
```
\marginparwidth 90.0pt
\marginparsep   11.0pt
\columnsep  10.0pt
\skip\footins  10.0pt plus 2.0pt minus 4.0pt
\hoffset 0.0pt
\voffset 0.0pt
\mag 1000
(1in=72.27pt, …
```
> Bugfix/OP-1455: Unable to Generate Envelopes

- app/lib/pdf.py
- app/lib/utils.py
- app/response/views.py
This PR resolves an issue when generating envelopes on OpenRecords.
The issue is caused by the `&` character, which is used in LaTeX to represent a tab mark. 
To resolve this, all occurrences of the `&` character are escaped (`\&`).
Difficulties in troubleshooting this error were caused by inadequate information in the `PDFGenerationException` class. Two arguments have been added (`stderr`and `stdout`) to provide additional information for errors caused by os subprocess calls. 
*Original Bug Report*
Error occurs when trying to generate envelopes on some requests.
Error displayed in the following traceback from pdflatex:
```
\marginparwidth 90.0pt
\marginparsep   11.0pt
\columnsep  10.0pt
\skip\footins  10.0pt plus 2.0pt minus 4.0pt
\hoffset 0.0pt
\voffset 0.0pt
\mag 1000
(1in=72.27pt, …
```
> Hotfix/OP-1455: Unable to Generate Envelopes

- app/auth/utils.py
- app/user/views.py
When a user first logs in to the application, their GUID is changed in the database to reflect the NYC.ID GUID. The ElasticSearch index needs to be updated for the requests where that user is assigned to make sure they can search for their own requests on the search page using the updated GUID.
Additionally, the search index is set to be updated when a user is changed from the agency administration page.
> Hotfix/OP-1451: Unable to View My Requests After First Login

- app/__init__.py
- app/templates/error/maintenance.html
- build_scripts/app_setup/app_setup.sh
- build_scripts/default/nginx_conf/sites/error.html
- build_scripts/default/nginx_conf/sites/maintenance.html
- build_scripts/default/nginx_conf/sites/openrecords_v2_0.conf
- build_scripts/web_setup/nginx_conf/sites/error.html
- build_scripts/web_setup/nginx_conf/sites/maintenance.html
- build_scripts/web_setup/nginx_conf/sites/openrecords_v2_0.conf
- maintenance.json
This pull request provides two implementations that can be used to limit access during a maintenance window.
Both implementations rely on cookies to provide the most basic form of authentication. If a user has the authorized_maintainer cookie set in their browser, they will be allowed to continue to the application, otherwise, the user is sent to a maintenance page with a 503 Status Code.
The two implementations are as follows:
**1) Flask (Preferred)**
Using the built in error handlers (abort), a user is sent to the maintenance page (with 503 Status Code) when a file is added to the `app.instance_path`. Currently the system looks for a `maintenance.json` file to exist in the instance path. 
The contents of the `maintenance.json` provide a description and an estimated outage time for the …
> Feature/OP-1465: Block Public Access to Environments During Maintenance Windows

- app/constants/schemas/agencies.schema
- app/request/views.py
- app/templates/request/_view_request_info.html
- data/agencies.json
- data/agencies_test.json
- data/custom_request_forms.json
I added an additional option to the custom_request_forms section of agency features.
`"expand_by_default": true` will cause the panels to be expanded when you first load the request page
`"expand_by_default": false` will cause the panels to be collapsed when you first load the request page
Make sure you reload the agency features column, otherwise the default value for `expand_by_default` will be `False`
> Feature/OP-1438: Display Custom Request Metadata on View Request Page

- app/agency/api/views.py
- app/models.py
- app/templates/custom_request_form_templates/form_description_template.html
- data/custom_request_forms.json
- migrations/versions/7e0434686370_added_custom_request_forms_table.py
This PR adds a new column in `CustomRequestForms` for `form_description`. If no description is needed for the form you can leave the `form_description` key in `custom_request_forms.json` as a blank string. You can use markdown in `form_description`.
If your database already has the custom request forms table please run the following commands:
`python manage.py db downgrade 445e50628f6b`
`python manage.py db upgrade dc926c74551d`
I made changes to an existing migration instead of creating a new one in order to keep a more logical order to the columns without dropping and creating a new table.
> Feature/OP-1505: Add Form Description for Custom Forms

- app/templates/request/view_request.html
- app/templates/response/add_note.html
Agency users with the `add_note` permission now have the ability to add notes after a request has been closed.
These notes will only be private.
> Feature/OP-1221: Add Notes after Closing

- app/static/js/upload/fileupload.js
- app/static/styles/base.css
- app/static/styles/new_request/new-request.css
- app/templates/request/fileupload_add_file.js.html
- app/templates/response/add_file.html
Alert box should be replaced with a modal dialog when uploading duplicate file(s) so that the message is always centered on the screen.
Acceptance Criteria:
- Modal dialog should appear for the file that is a duplicate for the current upload session.
Estimates:
Development: 2h
Code Review: 1h
QA: 1h
> bugfix/OP-998: Alert should be Modal when uploading duplicate file

- app/static/js/request/main.js
QA found a bug where if you had more than 10 forms they would show out of order in the request page. This is because the jinja `dictsort` function sorts alphabetically so it was sorting as:
`form_1, form_10, form_11, form_12, form_2, form_3, ...etc`
Fixed this by adding a leading 0 to forms/fields that were less than 10 so it will look like:
`form_01, form_02, form_03,..., form_10, form_11, form_12`
> Feature/OP-1438: Fixed sorting for forms/fields greater than 10

- app/models.py
This PR fixes a bug where the response rows disappear if you edit a response.
This bug occurs because we changed the response rows to order by event timestamps instead of response date_modified to preserve proper ordering on the front end. There is a query to get the event row associated with that response_id. Since editing a note (or any response) will create another event row with the same response_id, the query fails because it is expecting one row but multiple rows are returned back.
The fix is to query using .all() instead of .one() and take the newest of the list of events and use that to display on the frontend.
> Bugfix/OP-1516: Responses section values disappear after editing response

- app/request/api/views.py
- app/templates/request/new_request_agency.html
- data/agencies.json
- data/agencies_test.json
As an agency user, I am unable to see some responses when I am not assigned to a request.
This is due to a bug in the way responses are pulled from the database. 10 responses are pulled at a time, if the user is unable to view any of them because of their permissions, the number of results returned to the front-end is going to be less than 10, which means only two pages of results will be shown, and there will be no option to go to a third. This becomes an issue when there are more that 10 valid results, but only the order in which they are pulled results in some invalid results being pulled in the initial load.
Example:
Request has 11 responses. The most recent 9 are visible to the user, and the first response is visible to the user. On the first pull, the last response pulled will not …
> Hotfix/OP-1519: Unable to See Responses When Not Assigned to Request

- app/request/api/views.py
- app/templates/request/new_request_agency.html
- data/agencies.json
- data/agencies_test.json
As an agency user, I am unable to see some responses when I am not assigned to a request.
This is due to a bug in the way responses are pulled from the database. 10 responses are pulled at a time, if the user is unable to view any of them because of their permissions, the number of results returned to the front-end is going to be less than 10, which means only two pages of results will be shown, and there will be no option to go to a third. This becomes an issue when there are more that 10 valid results, but only the order in which they are pulled results in some invalid results being pulled in the initial load.
Example:
Request has 11 responses. The most recent 9 are visible to the user, and the first response is visible to the user. On the first pull, the last response pulled will not …
> Bugfix/OP-1519: Fix issues with query for responses

- app/agency/api/views.py
- app/static/js/request/main.js
- app/templates/custom_request_form_templates/date_template.html
- app/templates/custom_request_form_templates/input_template.html
- app/templates/custom_request_form_templates/radio_template.html
- app/templates/custom_request_form_templates/select_dropdown_template.html
- app/templates/custom_request_form_templates/select_multiple_template.html
- app/templates/custom_request_form_templates/textarea_template.html
- app/templates/custom_request_form_templates/time_template.html
- data/custom_request_forms.json
This PR adds tooltips, placeholders, popovers, and character counters to custom request form fields.
To add a tooltip add the following property to a field definition in the `custom_request_forms.json`:
`"tooltip": {
"title": "Sample tooltip title",
"content": "Sample tooltip content"
}`
To add a popover to any field except `radio` add the following property:
`"popover": {
"title": "Sample popover title",
"content": "Sample popover content"
}`
To add placeholder text to input and textarea fields add the following property:
`"placeholder": "Sample placeholder text"`
To add character counters to input and text area fields add the following property:
`"character_counter": true`
Character counters are tied to value in the `max_length` property
> Feature/OP-1501: Add Tooltips, Placeholders, Popovers, and Character Counters to Field Templates

- app/static/js/admin/main.js
- app/static/js/plugins/jquery.blockUI.js
- app/templates/admin/main.html
This PR uses the blockUI plugin to block the user row from any further action when it is being toggled between user and admin, or if the user is being removed from the agency. It will also block the user dropdown and add button row when adding a new user to the agency. The row will be blocked out until it receives the success call back from the Ajax function. This functionality may need to change depending on how we batch index in the other tickets.
> Feature/OP-1504: Spinner for Admin Changes

- app/auth/utils.py
Fixes an issue if a 404 is returned from the NYC.ID web services. 
When 404 is returned, web services does not provide JSON error message, so we don't need to check for it.
> Fix issue with json on 404 from web services

- app/static/js/request/main.js
- app/templates/response/add_acknowledgment.html
- app/templates/response/add_acknowledgment.js.html
- app/templates/response/add_extension.html
- app/templates/response/add_extension.js.html
Updates date format to 'mm/dd/yy' instead of 'yy-mm-dd'.
Removes duplicate code from add_extension.js.html (for the minDate in the datepicker)
Updates main.js holidaychecker to use proper date format.
> Hotfix/OP-1529: Resolve issues with custom date formats

- app/response/utils.py
- jobs.py
- manage.py
To test this functionality:
1) Import the latest Production DB backup into your local environment
2) Run `python manage.py fix_incorrect_key_events`
`# Fixes request_status_changed with key of 'request' instead of 'status'`
3) Run `python manage.py create_missing_request_status_changed_events` 
`# Inserts missing request_status_changed events`
Adds a CLI flag for updating the events table to include
request_status_changed events for requests closed between the current
date and the release of v2.3.
Additionally update the Events table to resolve an incorrect key for
request status changes (jobs.py) and use the REQ_DENIED event
instead of REQ_CLOSED for denials
Finally, adds a request_status_changed event for acknowledging a
request.
> bugfix/OP-1532: Add CLI flag for updating Events table

- requirements/common.txt
To resolve issue with PyCrypto.
As far as I can tell, we just need to run `pip uninstall -y pycrpto`.
We are not explicitly using it in our code and the dependency graph does not show any dependencies that rely on it. 
See:
- [pycrypto#253](https://github.com/dlitz/pycrypto/issues/253)
- [TElgamal/attack-on-pycrypto-elgamal](https://github.com/TElgamal/attack-on-pycrypto-elgamal)
- [pycrypto#275](https://github.com/dlitz/pycrypto/issues/275)
- [pycrypto#158](https://github.com/dlitz/pycrypto/issues/158)
> Hotfix/OP-1538: Remove `pycrypto` from requirements.

- requirements/common.txt
To resolve issue with PyCrypto.
As far as I can tell, we just need to run `pip uninstall -y pycrpto`.
We are not explicitly using it in our code and the dependency graph does not show any dependencies that rely on it. 
See:
- [pycrypto#253](https://github.com/dlitz/pycrypto/issues/253)
- [TElgamal/attack-on-pycrypto-elgamal](https://github.com/TElgamal/attack-on-pycrypto-elgamal)
- [pycrypto#275](https://github.com/dlitz/pycrypto/issues/275)
- [pycrypto#158](https://github.com/dlitz/pycrypto/issues/158)
> bugfix/OP-1538: Remove pycrypto from requirements.txt

- app/models.py
Responses created prior to the launch of OpenRecords v2.0 do not have entries in the events table. When filling in the responses section, we pull the timestamp for the event associated with a response. This obviously fails if the response has no associated event.
To resolve this issue, a check has been put in place to see if the event exists (the query returns a value instead of `None`). If the query returns `None` (actually an empty list), then we default to using the response date_modified, which is a close analogy to the event timestamp.
> Bugfix/OP-1546: Resolve Missing `timestamp` issue

- app/user/views.py
Caused by https://github.com//cityofnewyork/nycopenrecords/commit/739cc7c86f4a96bd40a86e434d970c0433276363
Users unable to modify mailing address because database attribute name is now _mailing_address.
DB_Utils must map the database attribute name when doing and update, not the name in the Python code.
> Bugfix/OP-1558: Not Able to Edit Anonymous Requester Mailing Address

- app/models.py
Add a check to make sure agency_request_summary_release_date exists before compare it to current date.
> Bugfix/OP-1562: Elasticsearch Reindex Fails for Agency Request Summary Release Date

- app/templates/_nyc_gov_header.html
- app/templates/navbar.html
Updates to region labels based on Walei's comments:
The labels need edits. The label itself should not have the word navigation in it. For example, Jaws announces "Main navigation navigation region." I would also change "Main navigation" to "Primary" navigation.
> Feature/OP-1175: Updated Region Labels

- app/static/js/request/faq.js
- app/static/js/request/main.js
- app/static/styles/faq.css
- app/templates/main/faq.html
- tests/functional/test_main.py
Main changes that happened in this PR:
- Clicking each FAQ link will scroll to the answer and give keyboard focus to the answer so the screen reader reads it.
- Clicking Back to Top will scroll up and give keyboard focus to the Frequent Asked Questions header.
> Feature/OP-1473: FAQ Accessibility

- app/response/views.py
- app/static/styles/add_acknowledgment.css
- app/static/styles/add_closing.css
- app/static/styles/add_denial.css
- app/static/styles/add_extension.css
- app/static/styles/view_request.css
- app/templates/request/view_request.html
- app/templates/response/add_acknowledgment.html
- app/templates/response/add_acknowledgment.js.html
- app/templates/response/add_closing.html
- app/templates/response/add_closing.js.html
- app/templates/response/add_denial.html
- app/templates/response/add_denial.js.html
- app/templates/response/add_extension.html
- app/templates/response/add_extension.js.html
- app/templates/response/add_file.html
- app/templates/response/add_file.js.html
- app/templates/response/add_instruction.html
- app/templates/response/add_instruction.js.html
- app/templates/response/add_link.html
- app/templates/response/add_link.js.html
- app/templates/response/add_note.html
- app/templates/response/add_note.js.html
- app/templates/response/add_reopening.html
- app/templates/response/add_reopening.js.html
- app/templates/response/add_user_request.html
- app/templates/response/add_user_request.js.html
- app/templates/response/edit_user_request.html
- app/templates/response/edit_user_request.js.html
This PR fixes a bug where emails were not being created and sent out if ajax calls didn't finish causing the backend to not receive the email content. I fixed this on both the backend and frontend.
For the backend it should flash a message if it doesn't receive one of the required fields such as the email summary. Previously some of the responses had a check that looked like:
`if response.get(field) is None:`
This causes python to throw an error because if the summary was missing it would be empty string and str type can't be compared to None type. So it would skip the message flash to stop the process and instead proceed to creating the response but not the associated Email object with it. So I fixed this by updating the check for the required to fields to make sure it's not empty …
> Bugfix/OP-1601: Emails Not Being Generated If AJAX Doesn't Finish

- app/user/views.py
This PR fixes the edit requester information functionality. 
The bug was caused by the check for `new_user_attrs.get('_mailing_address')`. If anything but the mailing address was changed, the if statement would still be `False` because we initialize the key `'_mailing_address'` as an empty dictionary. The fix is to initialize both `old_user_attrs` and `new_user_attrs` as a`defaultdict(dict)` so that the nested key (`'_mailing_address'`) is created in the for loop if address fields are changed.
> Bugfix/OP-1621: Editing Requester Information

- app/constants/user_attrs.py
- app/static/js/request/edit_requester_info.js
- app/user/views.py
Resolves the issue where the state was being set to None if the modal
dialog was closed before hitting submit. This was due to the way select
fields are handled. In order to get the value of a select field you need
to select the option value within the select field and get its value.
Without this, an empty string was being returned.
To resolve this, the state value, if present, is stored in JS on page
load and then used on the reset modal callback to restore the state.
To resolve the issue with the missing state and zipcode on the backend,
the UserAddressDict was modified to use the right keys when storing
the values of zip and state (in the case of state, it just wasn't
present in the initialization function.)
> BugFix/OP-1621: Resolve error with state and zip code.

- app/models.py
- app/templates/email_templates/email_confirmation.html
- app/templates/email_templates/email_request_status_changed.html
This PR adds "Request Type" to the confirmation email and the nightly request status report email if the agency is using custom request forms. We are using `description` as the value because the name of the custom form is appended to the request description.
Also included is the removal of `terms_of_use_accepted` from the `is_active` check. This is our temporary workaround until we fully implement the following ticket: https://nycrecords.atlassian.net/browse/OP-1653
> Feature/OP-1652: Add Request Type to Emails

- app/report/views.py
Added one day to `date_to` to account for all requests that come in during that day until midnight.
ex) 
date_to = 5/25/20 converts to 2020-06-25 04:00:00 UTC which is 2020-06-25 00:00:00 EST which is the start of the day (we will miss all requests submitted during the day)
date_to + timedelta(days=1) gives you 5/26/20 which converts to 2020-06-26 04:00:00 UTC which is 2020-06-26 00:00:00 EST which is the beginning of 5/26 (effectively end of day 5/25)
> Feature/OP-1661: Updated date conversion to account for EST to UTC difference

- app/jobs.py
- app/templates/email_templates/email_response_extension_cli.html
- openrecords.py
This PR adds a CLI command called `extend_requests` to extend all "Overdue" requests for a particular agency.
Example usage:
`flask extend-requests --agency_ein '0056' --agency_name 'New York City Police Department (NYPD)' --user_guid 'add1c7f91d7b49c4ab4cbf70683301ab' --extension_date '03/15/2022' --extension_reason 'test reason'`
Also created a CLI command called `update_request_statuses` to perform the update request statuses job as a cron job.
Example crontab:
`0 0 * * * source /opt/rh/rh-python35/enable && cd /vagrant && /home/vagrant/.virtualenvs/openrecords/bin/flask update-request-statuses >> /tmp/cron_output`
> Extend Requests and Update Request Statuses

- app/jobs.py
- app/main/views.py
- app/models.py
- app/request/views.py
- app/templates/email_templates/email_request_status_changed.html
- app/templates/email_templates/email_update_request_statuses_job_finished.html
- openrecords.py
This PR fixes the update request statuses job by adding the following optimizations:
- Replaced `request.requester.last_name` in email template with `request.requester_name`. Using `request.requester.last_name` is inefficient because each call does a query with joins. Instead we will use the requester name stored in the elasticsearch document.
- Instead of using `request.was_acknowledged` to determine if a request was acknowledged, we will perform an additional query at the beginning to get all overdue/due soon acknowledged requests and use set difference to find unacknowledged requests.
Ex) `agency_acknowledgments_overdue = list(set(requests_overdue) - set(agency_requests_overdue))`
Performance differences:
- Without optimizations it takes 2 hours 43 minutes to process around 74,000 …
> Fixed Update Request Statuses Job

- app/request/views.py
- app/static/js/request/new-request-agency.js
- app/static/js/request/new-request-user.js
- app/templates/request/new_request_anon.js.html
This PR adds the following to improve custom request form functionality:
- Backend validation to check that custom request form metadata exists on submission.
- Javascript to reload the page if loaded from a cached version. This fixes the issue with the browser back button not keeping the keeping the custom form and reverting back to the Request Description field.
Referenced: https://gomakethings.com/fixing-safaris-back-button-browser-cache-issue-with-vanilla-js/
> Fix Custom Forms Loading Part 2

- app/lib/email_utils.py
- app/request/utils.py
This PR fixes an issue with email bounce backs on Contact the Agency where certain email domains have security rules in place to prevent auto forwarding. Changing sender to be "donotreply@records.nyc.gov" instead of the user's email. User's email will now show up in the Reply To field.
Also changed `message` to `body` to get the full contents of the Contact the Agency form fields.
> Contact the Agency Bounce Back Fix

- app/models.py
- app/request/views.py
- app/templates/request/responses/modal_body/determinations.html
This PR fixes an issue with creating responses due to adding `release_date` to the `Responses` constructor. `release_date` was added so that we can manually set a release date for determinations (used in `add_closing_cli`) rather than the default 20 business days. Constructors and super functions updated for Files, Links, Instructions, Notes, Emails, Letters, Envelopes.
Other changes:
- Fixed an issue with acknowledgement/extension reason not showing because of wrong variable name.
- Fixed an issue with closed requests from an inactive agency not showing on view request page.
> Fix Super Function for Responses

- app/constants/schemas/agencies.schema
- app/response/utils.py
- app/templates/email_templates/email_response_acknowledgment.html
- app/templates/response/add_acknowledgment.js.html
This PR adds the functionality to use point of contact information in email templates. Currently only added to acknowledgement emails.
Point of contact notes:
- Turn on the feature by adding it to the agency features JSON. NYPD example below.
- By default, the current user's information will be used as the point of contact unless explicitly set.
- To select a point of contact, add/edit user and check off the point of contact option.
- Point of contact must have a Title and Phone Number set.
```
{"letters": {"footer": "<div style=\"text-align: left;\"><strong>Note: Due to issues caused by the COVID-19 pandemic there may be extensive delays, lasting up to one year, in determining your request.</strong></div>", "signature": {"text": "Very truly yours,<br/>{% if user.signature %}<img …
```
> Acknowledgement Email Point of Contact

- data/agencies.json
- data/custom_request_forms.json
SQL Inserts
```
INSERT INTO public.custom_request_forms (id, agency_ein, form_name, form_description, field_definitions, repeatable, category, minimum_required, "order", is_active) VALUES (20, '0072', 'Incarceration Dates', '', '[{"First Name": {"name": "doc-form1-field1", "type": "input", "required": true, "error_message": "<span class=\"glyphicon glyphicon-exclamation-sign\"></span>&nbsp;<strong>Error, First Name is required.</strong> Please provide a name."}}, {"Last Name": {"name": "doc-form1-field2", "type": "input", "required": true, "error_message": "<span class=\"glyphicon glyphicon-exclamation-sign\"></span>&nbsp;<strong>Error, Last Name is required.</strong> Please provide a name."}}, {"NYSID": {"name": "doc-form1-field3", "type": "input", "required": false}}, {"Book and Case …
```
> Added DOC Custom Request Forms
